up

diff --git a/.github/workflows/default-flow.yml b/.github/workflows/default-flow.yml
--- a/.github/workflows/default-flow.yml
+++ b/.github/workflows/default-flow.yml
@@ -39,14 +39,6 @@ jobs:
 
       - uses: actions/checkout@v3
 
-      # - name: Cache local Maven repository
-      #   uses: actions/cache@v2
-      #   with:
-      #     path: ~/.m2/repository
-      #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-maven-            
-      
       - uses: joshlong/java-version-export-github-action@v20
 
       - uses: actions/setup-java@v3
@@ -57,8 +49,8 @@ jobs:
 
       - run: echo "using $JAVA_MAJOR_VERSION"
 
-      # - name: Build
-      #   run: cd $GITHUB_WORKSPACE/.github/workflows ; ./build.sh
+      - name: Build
+        run: cd $GITHUB_WORKSPACE/.github/workflows ; ls -la  ./build.sh && ./build.sh  || die "could not invoke $GITHUB_WORKSPACE/.github/workflows"
 
       - name: Initiate Pipeline
         run: |
